# Generated by Django 5.2.4 on 2026-05-09 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(upload_to="avatars/", verbose_name="Аватар"),
        ),
    ]
