# projects/models
SKILL_NAME_MAX_LENGTH = 124
# projects/models
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_MAX_LENGTH = 6
STATUS_OPEN = "open"
STATUS_CLOSED = "closed"
STATUS_CHOICES = [
    (STATUS_OPEN, "Открыт"),
    (STATUS_CLOSED, "Закрыт"),
]
# projects/views
SKILL_SEARCH_LIMITATION = 10
# users/views
EMAIL_ERROR = "Такой email уже существует"
LOGIN_ERROR = "Неверный email или пароль"
# users/models
USER_NAME_MAX_LENGTH = 124
USER_SURNAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256
COLOR_BLUE = "#4A90E2"
COLOR_AQUAMARINE = "#50E3C2"
COLOR_GREEN = "#B8E986"
COLOR_ORANGE = "#F5A623"
COLOR_RED = "#D0021B"
COLOR_PURPLE = "#9013FE"
COLOR_DGREEN = "#417505"
COLOR_BROWN = "#8B572A"
COLOR_PINK = "#E94E77"
COLOR_GREY = "#4A4A4A"
USER_AVATAR_COLORS = [
    COLOR_BLUE,
    COLOR_AQUAMARINE,
    COLOR_GREEN,
    COLOR_ORANGE,
    COLOR_RED,
    COLOR_PURPLE,
    COLOR_DGREEN,
    COLOR_BROWN,
    COLOR_PINK,
    COLOR_GREY,
]
USER_AVATAR_SIZE = (200, 200)
USER_AVATAR_FONT_SIZE = 120
USER_AVATAR_FONT_PATH = "Neue_Haas_Grotesk_Display_Pro_75_Bold.otf"
# candf/functions
PAGINATOR_FOR_PAGE = 12
GIT_DOMAIN = "github.com"
GIT_URL_ERROR = "Введите URL."
USER_AVATAR_TEXT_COLOR = "#FFFFFF"
USER_AVATAR_TEXT_POSITION = (0, 0)
